### ISSUE TITLE
Bot showing duplicate locations

### ISSUE THREAD

**Issue by zulhfreelancer** [mohdaminyuddin/MyBanjirBot#1]
Source:

![0](https://cloud.githubusercontent.com/assets/3416976/21630481/8148b682-d229-11e6-8ece-f1daa46951e2.jpeg)

---

Bot:

![1](https://cloud.githubusercontent.com/assets/3416976/21630488/88afc244-d229-11e6-982e-1ae149245f83.png)

---

API:

![2](https://cloud.githubusercontent.com/assets/3416976/21630510/b83f7ac2-d229-11e6-9084-a5f9744fa7f8.png)

---

I think it would be great if we can add `nama_jalan` as well because user might get confused when they look at the `nama_laluan` duplicates.

**Comment by aminyuddin** [comment]
@zulhfreelancer is it better to just replace `nama_laluan` with `nama_jalan` instead of display both? If my assumption is correct,  `nama_laluan` can be considered as technical term for JKR and the `nama_jalan` is friendly name for it.
